### ISSUE TITLE
Traceback: ssh2.exceptions.AgentAuthenticationError: ('No identities match for user %s', b'<foo>')

### ISSUE THREAD

**Issue by odyssey4me** [directord/directord#123]
**Describe the bug**

With a starting catalog I thought the ssh config would be used where I set the key and username... but I was wrong.

```
jpretori@jpretori-mac directord % directord bootstrap --catalog ~/.local/etc/directord/catalog.yaml --catalog tools/directord-prod-bootstrap-catalog.yaml
INFO Loading server information
INFO Running bootstrap for hestia.local
Traceback (most recent call last):
  File "/usr/local/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.7.3', 'console_scripts', 'directord')())
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/main.py", line 566, in main
    _mixin.bootstrap_cluster()
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 627, in bootstrap_cluster
    self.bootstrap_run(job_def=s, catalog=catalog)
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 481, in bootstrap_run
    with utils.SSHConnect(
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/utils.py", line 169, in __init__
    self.session.agent_auth(username)
  File "ssh2/session.pyx", line 388, in ssh2.session.Session.agent_auth
  File "ssh2/agent.pyx", line 38, in ssh2.agent.agent_auth
ssh2.exceptions.AgentAuthenticationError: ('No identities match for user %s', b'jpretori')
```

Then I adjusted the catalog to have the user (root) and tried again.

```                                                        
jpretori@jpretori-mac directord % directord bootstrap --catalog ~/.local/etc/directord/catalog.yaml --catalog tools/directord-prod-bootstrap-catalog.yaml
INFO Loading server information
INFO Running bootstrap for hestia.local
Traceback (most recent call last):
  File "/usr/local/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.7.3', 'console_scripts', 'directord')())
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/main.py", line 566, in main
    _mixin.bootstrap_cluster()
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 627, in bootstrap_cluster
    self.bootstrap_run(job_def=s, catalog=catalog)
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 481, in bootstrap_run
    with utils.SSHConnect(
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/utils.py", line 169, in __init__
    self.session.agent_auth(username)
  File "ssh2/session.pyx", line 388, in ssh2.session.Session.agent_auth
  File "ssh2/agent.pyx", line 38, in ssh2.agent.agent_auth
ssh2.exceptions.AgentAuthenticationError: ('No identities match for user %s', b'root')
```

While there is likely a config issue here, I don't think the Traceback is helpful to any ordinary user. It might be better to catch this exception and provide an actionable error msg.

```
jpretori@jpretori-mac directord % cat ~/.local/etc/directord/catalog.yaml
directord_server:
  targets:
  - host: hestia.local
    port: 22
    username: root

directord_clients:
  args:
    port: 22
    username: root
    debug: yes
  targets:
  - host: hestia.local
```

Note that I also tried using the key file argument to no avail.

```
jpretori@jpretori-mac directord % directord bootstrap --catalog ~/.local/etc/directord/catalog.yaml --catalog tools/directord-prod-bootstrap-catalog.yaml --key-file ~/.ssh/id_rsa
INFO Loading server information
INFO Running bootstrap for hestia.local
Traceback (most recent call last):
  File "/usr/local/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.7.3', 'console_scripts', 'directord')())
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/main.py", line 566, in main
    _mixin.bootstrap_cluster()
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 627, in bootstrap_cluster
    self.bootstrap_run(job_def=s, catalog=catalog)
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/mixin.py", line 481, in bootstrap_run
    with utils.SSHConnect(
  File "/usr/local/Cellar/directord/0.7.3/libexec/lib/python3.9/site-packages/directord/utils.py", line 165, in __init__
    self.session.userauth_publickey_fromfile(username, key_file)
  File "ssh2/session.pyx", line 232, in ssh2.session.Session.userauth_publickey_fromfile
  File "ssh2/utils.pyx", line 166, in ssh2.utils.handle_error_codes
ssh2.exceptions.AuthenticationError
```

I'd prefer to see:
- The system respect my ssh config, rather than force me to respecify the config.
- Some way to identify what is going on - debug mode perhaps?

Other notes:
- I can't seem to figure out how to enable any form of debug.
- I can ssh from jpretori-mac to root@hestia.local using ~/.ssh/id_rsa

**Operating System:**
 - OS: Mac OS X Big Sur
 - Directord 0.7.3

**Python Version:**
 - Python 3.9.6

**Additional context**

**Comment by cloudnull** [comment]
I'll look into this, as for debug the following command should work

``` shell
directord --debug bootstrap --catalog ~/.local/etc/directord/catalog.yaml --catalog tools/directord-prod-bootstrap-catalog.yaml --key-file ~/.ssh/id_rsa
```
