### ISSUE TITLE
tabulate dep missing from rpm

### ISSUE THREAD

**Issue by mwhahaha** [directord/directord#354]
**Describe the bug**
Using the built rpms from a PR and installing them locally results in a tabulate module not found error when you attempt to bootstrap

**To Reproduce**
```
[stack@task-core-0 directord]$ sudo dnf localinstall -y ~/directord/directord*.noarch.rpm ~/directord/python3-ssh-python-0.9.0-1.el8.x86_64.rpm
[stack@task-core-0 directord]$ directord --debug bootstrap --catalog ~/task-core/examples/directord/basic/directord_catalog.yaml --catalog /usr/share/directord/tools/directord-dev-bootstrap-zmq.yaml 
Traceback (most recent call last):
  File "/usr/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.11.3', 'console_scripts', 'directord')())
  File "/usr/bin/directord", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/directord/main.py", line 28, in <module>
    from directord import bootstrap
  File "/usr/lib/python3.6/site-packages/directord/bootstrap.py", line 27, in <module>
    from directord import utils
  File "/usr/lib/python3.6/site-packages/directord/utils.py", line 25, in <module>
    import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

**Comment by mwhahaha** [comment]
closed via #352 352
